import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { join, relative, sep } from "node:path";
import { describe, it } from "node:test";

import {
  createRepository,
  createTemporaryDirectory,
  git,
  REPOSITORY_ROOT,
  runCli,
} from "./helpers.mjs";

const SHA = "cb829e2f0c1d4a5b6e7f8091a2b3c4d5e6f70812";
const ZERO = "0000000000000000000000000000000000000000";
const PULL_REQUEST_WORKFLOW = ".github/workflows/style-guide-pull-request.yml";
const PUSH_WORKFLOW = ".github/workflows/style-guide-push.yml";
const SKILL = ".claude/skills/style-guide/SKILL.md";
const PRE_COMMIT = ".husky/pre-commit";
const PRE_PUSH = ".husky/pre-push";
const SETUP_FILES = [
  PULL_REQUEST_WORKFLOW,
  PUSH_WORKFLOW,
  SKILL,
  PRE_COMMIT,
  PRE_PUSH,
];
const CUSTOM_CONFIG = {
  branchFlow: {
    workBranchPrefixes: ["feat", "ops"],
    longLivedBranches: ["staging"],
  },
};

function writeJson(directory, name, value) {
  writeFileSync(join(directory, name), `${JSON.stringify(value, null, 2)}\n`);
}

/** A repository whose package.json and Biome configuration leave `init` nothing to report. */
function createConsumerRepository() {
  const directory = createRepository("feat/setup");
  writeJson(directory, "package.json", {
    name: "consumer",
    private: true,
    scripts: { prepare: "husky" },
    devDependencies: {
      "@biomejs/biome": "2.5.15",
      "@pleand-inc/style-guide": "1.2.3",
      husky: "9.1.7",
    },
  });
  writeJson(directory, "biome.json", {
    extends: ["@pleand-inc/style-guide/biome"],
  });
  return directory;
}

function read(directory, path) {
  return readFileSync(join(directory, path), "utf8");
}

function lines(text) {
  return text.split("\n").filter((line) => line !== "");
}

describe("style-guide", () => {
  it("prints the usage with every command for --help, -h and no command", () => {
    for (const cliArguments of [["--help"], ["-h"], []]) {
      const result = runCli(cliArguments);
      assert.equal(result.status, 0);
      assert.equal(result.stderr, "");
      assert.match(result.stdout, /^Usage: style-guide <command>/);
      for (const command of [
        "init",
        "check",
        "check-commit",
        "check-push",
        "check-pull-request",
        "merge <pr-number>",
      ]) {
        assert.match(
          result.stdout,
          new RegExp(`^ {2}${command} `, "m"),
          command,
        );
      }
      assert.match(result.stdout, /^ {2}check-landed-commit /m);
    }
  });

  it("prints the usage on stderr and exits 2 for an unknown command", () => {
    const result = runCli(["chekc"]);
    assert.equal(result.status, 2);
    assert.equal(result.stdout, "");
    assert.match(
      result.stderr,
      /^style-guide: unknown command 'chekc'\n\nUsage: style-guide <command>/,
    );
  });

  it("exits 2 when a command that takes no arguments gets one", () => {
    const result = runCli(["check-pull-request", "develop"], {
      env: { BASE_REF: "develop", HEAD_REF: "feat/a" },
    });
    assert.equal(result.status, 2);
    assert.match(
      result.stderr,
      /^style-guide: check-pull-request takes no arguments \(got: develop\)\n$/,
    );
  });
});

describe("style-guide init and check: a repository that needs nothing by hand", () => {
  it("init creates the owned files and the hooks, a second init changes nothing, and check passes", () => {
    const directory = createConsumerRepository();

    const first = runCli(["init"], { cwd: directory });
    assert.equal(first.stderr, "");
    assert.deepEqual(
      lines(first.stdout),
      SETUP_FILES.map((path) => `created    ${path}`),
    );
    assert.equal(first.status, 0);
    for (const path of [PULL_REQUEST_WORKFLOW, PUSH_WORKFLOW]) {
      assert.match(
        read(directory, path),
        /^# Generated by `style-guide init`\. Do not edit by hand/,
      );
    }
    assert.match(read(directory, SKILL), /^---\nname: style-guide\n/);
    assert.equal(
      read(directory, PRE_COMMIT),
      "node_modules/.bin/style-guide check-commit\nnode_modules/.bin/biome check --staged --no-errors-on-unmatched\n",
    );
    assert.equal(
      read(directory, PRE_PUSH),
      "node_modules/.bin/style-guide check-push\n",
    );

    const second = runCli(["init"], { cwd: directory });
    assert.deepEqual(
      lines(second.stdout),
      SETUP_FILES.map((path) => `unchanged  ${path}`),
    );
    assert.equal(second.status, 0);

    const check = runCli(["check"], { cwd: directory });
    assert.deepEqual(check, {
      status: 0,
      stdout: "style-guide check: the setup is current\n",
      stderr: "",
    });
  });

  it("the skill lists the files under this package's rules directory, sorted", () => {
    const directory = createConsumerRepository();
    runCli(["init"], { cwd: directory });
    const listed = lines(read(directory, SKILL))
      .filter((line) =>
        line.startsWith("- `node_modules/@pleand-inc/style-guide/rules/"),
      )
      .map((line) =>
        line.slice("- `node_modules/@pleand-inc/style-guide/rules/".length, -1),
      );
    const rulesDirectory = join(REPOSITORY_ROOT, "rules");
    const present = execFileSync("find", [rulesDirectory, "-type", "f"], {
      encoding: "utf8",
    })
      .split("\n")
      .filter((path) => path !== "")
      .map((path) => relative(rulesDirectory, path).split(sep).join("/"));
    assert.deepEqual(listed, present.sort());
    assert.ok(listed.includes("typescript/types/RULES.md"));
  });
});

describe("style-guide init and check: files that were changed or deleted", () => {
  it("check fails naming an edited owned file, and init rewrites it", () => {
    const directory = createConsumerRepository();
    runCli(["init"], { cwd: directory });
    const generated = read(directory, PULL_REQUEST_WORKFLOW);
    writeFileSync(
      join(directory, PULL_REQUEST_WORKFLOW),
      generated.replace("timeout-minutes: 5", "timeout-minutes: 60"),
    );

    const check = runCli(["check"], { cwd: directory });
    assert.deepEqual(check, {
      status: 1,
      stdout: "",
      stderr: `differs: ${PULL_REQUEST_WORKFLOW} (run style-guide init)\n`,
    });

    const init = runCli(["init"], { cwd: directory });
    assert.equal(init.status, 0);
    assert.equal(lines(init.stdout)[0], `rewritten  ${PULL_REQUEST_WORKFLOW}`);
    assert.equal(
      lines(init.stdout).filter((line) => line.startsWith("unchanged")).length,
      4,
    );
    assert.equal(read(directory, PULL_REQUEST_WORKFLOW), generated);
    assert.equal(runCli(["check"], { cwd: directory }).status, 0);
  });

  it("check fails naming a deleted hook and a deleted skill", () => {
    const directory = createConsumerRepository();
    runCli(["init"], { cwd: directory });
    rmSync(join(directory, PRE_COMMIT));
    rmSync(join(directory, SKILL));

    const check = runCli(["check"], { cwd: directory });
    assert.equal(check.status, 1);
    assert.deepEqual(lines(check.stderr), [
      `missing: ${SKILL} (run style-guide init)`,
      `missing: ${PRE_COMMIT} (run style-guide init)`,
    ]);
    assert.equal(existsSync(join(directory, PRE_COMMIT)), false);
  });

  it("init leaves an existing hook without the required line untouched and prints the line to add", () => {
    const directory = createConsumerRepository();
    mkdirSync(join(directory, ".husky"));
    const ownHook =
      "#!/bin/sh\nnpm test\nnode_modules/.bin/biome check --staged\n";
    writeFileSync(join(directory, PRE_COMMIT), ownHook);

    const init = runCli(["init"], { cwd: directory });
    assert.equal(init.status, 1);
    assert.deepEqual(lines(init.stdout).slice(3), [
      `incomplete ${PRE_COMMIT}`,
      `created    ${PRE_PUSH}`,
      `manual: add this line to ${PRE_COMMIT}: node_modules/.bin/style-guide check-commit`,
    ]);
    assert.equal(read(directory, PRE_COMMIT), ownHook);

    const check = runCli(["check"], { cwd: directory });
    assert.equal(check.status, 1);
    assert.equal(
      check.stderr,
      `manual: add this line to ${PRE_COMMIT}: node_modules/.bin/style-guide check-commit\n`,
    );

    writeFileSync(
      join(directory, PRE_COMMIT),
      `${ownHook}node_modules/.bin/style-guide check-commit\n`,
    );
    assert.equal(runCli(["init"], { cwd: directory }).status, 0);
    assert.equal(runCli(["check"], { cwd: directory }).status, 0);
  });
});

describe("style-guide init and check: what init does not change", () => {
  it("init reports what it does not change in package.json and biome.json, and still writes its own files", () => {
    const directory = createRepository("feat/setup");
    const manifest =
      '{ "name": "consumer", "devDependencies": { "@pleand-inc/style-guide": "^1.2.3" } }\n';
    writeFileSync(join(directory, "package.json"), manifest);

    const init = runCli(["init"], { cwd: directory });
    assert.equal(init.status, 1);
    assert.deepEqual(lines(init.stdout).slice(5), [
      "manual: package.json: add husky to devDependencies",
      'manual: package.json: add a prepare script that runs husky ("prepare": "husky")',
      "manual: package.json: pin @pleand-inc/style-guide in devDependencies to an exact version or a git spec " +
        '(found "^1.2.3")',
      'manual: biome.json: extend the shared configuration ("extends": ["@pleand-inc/style-guide/biome"])',
    ]);
    assert.equal(read(directory, "package.json"), manifest);
    assert.equal(existsSync(join(directory, "biome.json")), false);
    for (const path of SETUP_FILES)
      assert.equal(existsSync(join(directory, path)), true, path);

    const check = runCli(["check"], { cwd: directory });
    assert.equal(check.status, 1);
    assert.deepEqual(lines(check.stderr), lines(init.stdout).slice(5));
  });

  it("init and check exit 2 outside a repository root and write nothing", () => {
    const directory = createTemporaryDirectory("style-guide-not-a-repository-");
    for (const command of ["init", "check"]) {
      const result = runCli([command], { cwd: directory });
      assert.equal(result.status, 2);
      assert.match(
        result.stderr,
        new RegExp(`^style-guide: ${command} runs from the repository root`),
      );
    }
    assert.deepEqual(readdirSync(directory), []);
  });

  it("init and check exit 2 on a configuration they cannot use, before writing anything", () => {
    const directory = createConsumerRepository();
    writeJson(directory, "style-guide.config.json", {
      branchFlow: { workBranchPrefixes: [] },
    });
    for (const command of ["init", "check"]) {
      const result = runCli([command], { cwd: directory });
      assert.equal(result.status, 2);
      assert.match(
        result.stderr,
        /'branchFlow\.workBranchPrefixes' must list at least one prefix/,
      );
    }
    assert.equal(existsSync(join(directory, ".github")), false);
  });
});

describe("style-guide check-commit", () => {
  for (const branch of ["master", "develop"]) {
    it(`exits 1 with a one-line reason on ${branch}`, () => {
      const result = runCli(["check-commit"], {
        cwd: createRepository(branch),
      });
      assert.equal(result.status, 1);
      assert.equal(result.stdout, "");
      assert.match(
        result.stderr,
        new RegExp(
          `^style-guide check-commit: commit on '${branch}' is blocked: .*\\n$`,
        ),
      );
      assert.equal(lines(result.stderr).length, 1);
    });
  }

  for (const branch of ["feat/x", "staging", "worktree-x"]) {
    it(`exits 0 on ${branch}`, () => {
      assert.deepEqual(
        runCli(["check-commit"], { cwd: createRepository(branch) }),
        {
          status: 0,
          stdout: "",
          stderr: "",
        },
      );
    });
  }

  it("exits 0 on a detached HEAD", () => {
    const directory = createRepository("master");
    const identity = [
      "-c",
      "user.name=Test",
      "-c",
      "user.email=test@example.com",
    ];
    git(directory, [
      ...identity,
      "commit",
      "--quiet",
      "--allow-empty",
      "--no-verify",
      "-m",
      "chore: start",
    ]);
    git(directory, ["checkout", "--quiet", "--detach"]);
    assert.equal(git(directory, ["branch", "--show-current"]), "");
    assert.equal(runCli(["check-commit"], { cwd: directory }).status, 0);
  });

  it("names the configured prefixes in the way out", () => {
    const directory = createRepository("develop");
    writeJson(directory, "style-guide.config.json", CUSTOM_CONFIG);
    const result = runCli(["check-commit"], { cwd: directory });
    assert.equal(result.status, 1);
    assert.match(result.stderr, /Commit on a feat\|ops\/<slug> branch/);
  });

  it("exits 2 naming the key when style-guide.config.json cannot be used", () => {
    const directory = createRepository("feat/x");
    writeJson(directory, "style-guide.config.json", {
      branchFlow: { longLived: [] },
    });
    const result = runCli(["check-commit"], { cwd: directory });
    assert.equal(result.status, 2);
    assert.match(
      result.stderr,
      /^style-guide: style-guide\.config\.json: unknown key 'branchFlow\.longLived'/,
    );
  });
});

/** One line of git's pre-push input: a push of a branch that the remote does not have yet. */
const pushOf = (branch) =>
  `refs/heads/${branch} ${SHA} refs/heads/${branch} ${ZERO}\n`;

describe("style-guide check-push", () => {
  it("exits 0 for work branches and tags", () => {
    const input = `${pushOf("feat/login")}${pushOf("docs/readme")}refs/tags/v1.0.0 ${SHA} refs/tags/v1.0.0 ${ZERO}\n`;
    const result = runCli(["check-push"], {
      cwd: createRepository("feat/login"),
      input,
    });
    assert.deepEqual(result, { status: 0, stdout: "", stderr: "" });
  });

  it("exits 0 when git pushes nothing", () => {
    assert.equal(
      runCli(["check-push"], { cwd: createRepository("feat/login"), input: "" })
        .status,
      0,
    );
  });

  it("exits 1 with one line per blocked ref: master, develop, a delete, and a name outside the flow", () => {
    const input = [
      pushOf("feat/login"),
      pushOf("master"),
      pushOf("develop"),
      `(delete) ${ZERO} refs/heads/develop ${SHA}\n`,
      pushOf("wip"),
    ].join("");
    const result = runCli(["check-push"], {
      cwd: createRepository("feat/login"),
      input,
    });
    assert.equal(result.status, 1);
    assert.equal(result.stdout, "");
    const reported = lines(result.stderr);
    assert.equal(reported.length, 4);
    assert.match(
      reported[0],
      /^style-guide check-push: direct push to 'master' is blocked/,
    );
    assert.match(
      reported[1],
      /^style-guide check-push: direct push to 'develop' is blocked/,
    );
    assert.match(
      reported[2],
      /^style-guide check-push: direct delete of 'develop' is blocked/,
    );
    assert.match(
      reported[3],
      /^style-guide check-push: push to 'wip' is blocked: branch names must be feat\|fix/,
    );
  });

  it("follows style-guide.config.json: a long-lived branch and an extra prefix pass, a dropped prefix does not", () => {
    const directory = createRepository("feat/login");
    assert.equal(
      runCli(["check-push"], { cwd: directory, input: pushOf("staging") })
        .status,
      1,
    );
    assert.equal(
      runCli(["check-push"], { cwd: directory, input: pushOf("ops/deploy") })
        .status,
      1,
    );

    writeJson(directory, "style-guide.config.json", CUSTOM_CONFIG);
    assert.equal(
      runCli(["check-push"], { cwd: directory, input: pushOf("staging") })
        .status,
      0,
    );
    assert.equal(
      runCli(["check-push"], { cwd: directory, input: pushOf("ops/deploy") })
        .status,
      0,
    );
    assert.equal(
      runCli(["check-push"], { cwd: directory, input: pushOf("docs/readme") })
        .status,
      1,
    );
    assert.equal(
      runCli(["check-push"], { cwd: directory, input: pushOf("master") })
        .status,
      1,
    );
  });
});

describe("style-guide check-pull-request", () => {
  const passing = [
    { BASE_REF: "develop", HEAD_REF: "feat/login" },
    { BASE_REF: "master", HEAD_REF: "develop" },
    { BASE_REF: "feat/login", HEAD_REF: "feat/login-form" },
    { GITHUB_BASE_REF: "develop", GITHUB_HEAD_REF: "fix/typo" },
    {
      BASE_REF: "",
      HEAD_REF: "",
      GITHUB_BASE_REF: "develop",
      GITHUB_HEAD_REF: "fix/typo",
    },
  ];
  for (const env of passing) {
    it(`exits 0 for ${JSON.stringify(env)}`, () => {
      const result = runCli(["check-pull-request"], {
        cwd: createRepository("feat/x"),
        env,
      });
      assert.equal(result.status, 0);
      assert.match(
        result.stdout,
        /^style-guide check-pull-request: \S+ -> \S+ follows the flow\n$/,
      );
    });
  }

  const failing = [
    {
      env: { BASE_REF: "master", HEAD_REF: "feat/login" },
      reason: /master takes only develop/,
    },
    {
      env: { BASE_REF: "develop", HEAD_REF: "wip" },
      reason: /the head 'wip' must be feat\|fix\|chore\|docs\/<slug>/,
    },
    {
      env: { BASE_REF: "develop", HEAD_REF: "master" },
      reason: /the head 'master' must be/,
    },
    {
      env: { BASE_REF: "release", HEAD_REF: "feat/login" },
      reason: /base 'release' is not part of the flow/,
    },
  ];
  for (const { env, reason } of failing) {
    it(`exits 1 with the reason for ${JSON.stringify(env)}`, () => {
      const result = runCli(["check-pull-request"], {
        cwd: createRepository("feat/x"),
        env,
      });
      assert.equal(result.status, 1);
      assert.match(result.stderr, reason);
      assert.equal(lines(result.stderr).length, 1);
    });
  }

  it("prefers BASE_REF and HEAD_REF over the GITHUB_ variables", () => {
    const env = {
      BASE_REF: "master",
      HEAD_REF: "feat/login",
      GITHUB_BASE_REF: "develop",
      GITHUB_HEAD_REF: "feat/login",
    };
    assert.equal(
      runCli(["check-pull-request"], { cwd: createRepository("feat/x"), env })
        .status,
      1,
    );
  });

  it("exits 2 when the base or the head is not given", () => {
    for (const env of [
      {},
      { BASE_REF: "develop" },
      { GITHUB_HEAD_REF: "feat/login" },
    ]) {
      const result = runCli(["check-pull-request"], {
        cwd: createRepository("feat/x"),
        env,
      });
      assert.equal(result.status, 2, JSON.stringify(env));
      assert.match(
        result.stderr,
        /^style-guide: check-pull-request needs the pull request's base and head branch/,
      );
    }
  });

  it("follows style-guide.config.json: a long-lived branch is never a head, an extra prefix is", () => {
    const directory = createRepository("feat/x");
    writeJson(directory, "style-guide.config.json", CUSTOM_CONFIG);
    const run = (env) =>
      runCli(["check-pull-request"], { cwd: directory, env });
    assert.equal(
      run({ BASE_REF: "develop", HEAD_REF: "ops/deploy" }).status,
      0,
    );
    assert.equal(run({ BASE_REF: "develop", HEAD_REF: "staging" }).status, 1);
    assert.equal(run({ BASE_REF: "master", HEAD_REF: "staging" }).status, 1);
    assert.equal(
      run({ BASE_REF: "staging", HEAD_REF: "feat/login" }).status,
      1,
    );
  });
});
