import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, it } from "node:test";

import {
  checkReport,
  HOOKS,
  INSPECTED_PATHS,
  initPlan,
  inspectSetup,
  isPinnedSpec,
  missingHookLines,
  ownedFiles,
  PULL_REQUEST_WORKFLOW_PATH,
  PUSH_WORKFLOW_PATH,
  packageManualSteps,
  SKILL_PATH,
} from "../../cli/lib/setup.mjs";
import {
  pullRequestWorkflowFile,
  pushWorkflowFile,
  skillFile,
  workflowRunLines,
} from "../../cli/lib/templates.mjs";
import { REPOSITORY_ROOT } from "./helpers.mjs";

const RULE_FILES = ["EXAMPLES.md", "RULES.md"];
const PRE_COMMIT_PATH = ".husky/pre-commit";
const PRE_PUSH_PATH = ".husky/pre-push";
const CHECK_COMMIT_LINE = "node_modules/.bin/style-guide check-commit";
const BIOME_LINE =
  "node_modules/.bin/biome check --staged --no-errors-on-unmatched";
const CHECK_PUSH_LINE = "node_modules/.bin/style-guide check-push";
const COMPLETE_MANIFEST = {
  scripts: { prepare: "husky" },
  devDependencies: { "@pleand-inc/style-guide": "1.2.3", husky: "9.1.7" },
};

function manifestText(overrides) {
  return JSON.stringify({ ...COMPLETE_MANIFEST, ...overrides });
}

function contentOf(path) {
  const file = ownedFiles(RULE_FILES).find((owned) => owned.path === path);
  assert.ok(file, `${path} is not an owned file`);
  return file.content;
}

/** The files of a repository that `init` has set up and that needs no manual step. */
function completeRepositoryFiles() {
  return new Map([
    ...ownedFiles(RULE_FILES).map(({ path, content }) => [path, content]),
    [PRE_COMMIT_PATH, `${CHECK_COMMIT_LINE}\n${BIOME_LINE}\n`],
    [PRE_PUSH_PATH, `${CHECK_PUSH_LINE}\n`],
    ["package.json", manifestText({})],
    ["biome.json", '{ "extends": ["@pleand-inc/style-guide/biome"] }'],
  ]);
}

function usesLines(workflowText) {
  return workflowText
    .split("\n")
    .filter((line) => line.includes("uses:"))
    .map((line) => line.trim().replace(/^- /, ""));
}

const pullRequest = pullRequestWorkflowFile();
const push = pushWorkflowFile();

describe("both generated workflows", () => {
  for (const [name, workflow] of [
    ["pull request", pullRequest],
    ["push", push],
  ]) {
    it(`${name}: starts with a comment that says it is generated and not edited by hand`, () => {
      const firstLine = workflow.split("\n")[0];
      assert.match(
        firstLine,
        /^# Generated by `style-guide init`\. Do not edit by hand/,
      );
    });

    it(`${name}: grants nothing at the top level and limits every job to five minutes`, () => {
      assert.match(workflow, /^permissions: \{\}$/m);
      const jobCount = workflow.match(/^ {4}runs-on: ubuntu-latest$/gm).length;
      assert.equal(
        workflow.match(/^ {4}timeout-minutes: 5$/gm).length,
        jobCount,
      );
      assert.equal(workflow.match(/^ {4}permissions:$/gm).length, jobCount);
    });

    it(`${name}: pins the actions to the commits .github/workflows/test.yml uses`, () => {
      const testWorkflow = readFileSync(
        join(REPOSITORY_ROOT, ".github", "workflows", "test.yml"),
        "utf8",
      );
      const pinned = usesLines(testWorkflow);
      assert.equal(pinned.length, 2);
      assert.deepEqual([...new Set(usesLines(workflow))], pinned);
    });

    it(`${name}: runs on the current LTS of Node and skips the Biome peer dependency`, () => {
      const jobCount = workflow.match(/^ {4}runs-on: ubuntu-latest$/gm).length;
      assert.equal(
        workflow.match(/^ {10}node-version: lts\/\*$/gm).length,
        jobCount,
      );
      assert.equal(
        workflow.match(/^ {10}NPM_CONFIG_LEGACY_PEER_DEPS: "true"$/gm).length,
        jobCount,
      );
    });

    it(`${name}: never installs the repository's own dependencies and names no version`, () => {
      assert.doesNotMatch(workflow, /npm (ci|install)|pnpm|yarn/);
      assert.doesNotMatch(workflow, /@pleand-inc\/style-guide@\d/);
    });

    it(`${name}: ends with one newline and has no tab or trailing space`, () => {
      assert.match(workflow, /[^\n]\n$/);
      assert.doesNotMatch(workflow, /\t| \n/);
    });
  }
});

describe("the generated pull request workflow", () => {
  it("runs on the four pull request activity types", () => {
    assert.match(
      pullRequest,
      /^on:\n {2}pull_request:\n {4}types: \[opened, reopened, synchronize, edited\]\n/m,
    );
    assert.doesNotMatch(pullRequest, /^ {2}push:/m);
  });

  it("has the pairing job and the setup job, each with read-only contents", () => {
    assert.match(
      pullRequest,
      /^ {2}pull-request-pairing:\n {4}name: pull request pairing$/m,
    );
    assert.match(
      pullRequest,
      /^ {2}style-guide-setup:\n {4}name: style guide setup$/m,
    );
    assert.equal(pullRequest.match(/^ {6}contents: read$/gm).length, 2);
    assert.doesNotMatch(pullRequest, /write|pull-requests:/);
  });

  it("passes the base and head through the environment, not through the script", () => {
    assert.match(pullRequest, /^ {10}BASE_REF: \$\{\{ github\.base_ref \}\}$/m);
    assert.match(pullRequest, /^ {10}HEAD_REF: \$\{\{ github\.head_ref \}\}$/m);
    assert.match(pullRequest, /-- style-guide check-pull-request$/m);
    assert.match(pullRequest, /-- style-guide check$/m);
    const runLines = pullRequest
      .split("\n")
      .filter((line) => line.includes("npm exec") || line.includes("spec="));
    assert.equal(
      runLines.some((line) => line.includes("${{")),
      false,
    );
  });
});

describe("the generated push workflow", () => {
  it("runs on pushes to master and develop only", () => {
    assert.match(
      push,
      /^on:\n {2}push:\n {4}branches:\n {6}- master\n {6}- develop\n\n/m,
    );
    assert.doesNotMatch(push, /pull_request:/);
  });

  it("has the landed commit job, which may read contents and pull requests", () => {
    assert.match(push, /^ {2}landed-commit:\n {4}name: landed commit$/m);
    assert.match(
      push,
      /^ {4}permissions:\n {6}contents: read\n {6}pull-requests: read\n {4}steps:$/m,
    );
    assert.match(push, /^ {10}GITHUB_TOKEN: \$\{\{ github\.token \}\}$/m);
    assert.match(push, /-- style-guide check-landed-commit$/m);
    assert.doesNotMatch(push, /write/);
  });
});

describe("workflowRunLines", () => {
  it("reads the pinned spec from package.json and runs the command from it", () => {
    assert.deepEqual(workflowRunLines("check"), [
      "spec=\"$(node -p \"const v = require('./package.json').devDependencies['@pleand-inc/style-guide']; " +
        "/^[0-9]/.test(v) ? '@pleand-inc/style-guide@' + v : v\")\"",
      'npm exec --yes --package="$spec" -- style-guide check',
    ]);
  });
});

describe("the generated skill", () => {
  const skill = skillFile(RULE_FILES);

  it("starts with front matter that names the skill and says when to use it", () => {
    const lines = skill.split("\n");
    assert.deepEqual(lines.slice(0, 2), ["---", "name: style-guide"]);
    assert.match(
      lines[2],
      /^description: Use when writing, editing or reviewing code in this repository/,
    );
    assert.match(lines[2], /branch|merging/);
    assert.doesNotMatch(lines[2].slice("description: ".length), /: /);
    assert.equal(lines[3], "---");
  });

  it("says right after the front matter that it is generated and not edited by hand", () => {
    assert.match(
      skill.split("\n")[5],
      /^<!-- Generated by `style-guide init`\. Do not edit by hand.* -->$/,
    );
  });

  it("lists every rule file it is given under the installed package, in the order given", () => {
    const listed = skill
      .split("\n")
      .filter((line) =>
        line.startsWith("- `node_modules/@pleand-inc/style-guide/rules/"),
      );
    assert.deepEqual(listed, [
      "- `node_modules/@pleand-inc/style-guide/rules/EXAMPLES.md`",
      "- `node_modules/@pleand-inc/style-guide/rules/RULES.md`",
    ]);
    const nested = skillFile(["RULES.md", "typescript/TYPES.md"]);
    assert.match(
      nested,
      /^- `node_modules\/@pleand-inc\/style-guide\/rules\/typescript\/TYPES\.md`$/m,
    );
    assert.doesNotMatch(nested, /EXAMPLES\.md/);
  });

  it("points at the branch flow, the merge command, and says rules are not edited here", () => {
    assert.match(
      skill,
      /`node_modules\/@pleand-inc\/style-guide\/process\/branch-flow\.md`/,
    );
    assert.match(skill, /`node_modules\/\.bin\/style-guide merge <번호>`/);
    assert.match(skill, /규칙은 이 저장소에서 고치지 않습니다\./);
  });
});

describe("ownedFiles", () => {
  it("is the two workflows and the skill", () => {
    assert.deepEqual(
      ownedFiles(RULE_FILES).map((file) => file.path),
      [
        ".github/workflows/style-guide-pull-request.yml",
        ".github/workflows/style-guide-push.yml",
        ".claude/skills/style-guide/SKILL.md",
      ],
    );
    assert.equal(
      contentOf(PULL_REQUEST_WORKFLOW_PATH),
      pullRequestWorkflowFile(),
    );
    assert.equal(contentOf(PUSH_WORKFLOW_PATH), pushWorkflowFile());
    assert.equal(contentOf(SKILL_PATH), skillFile(RULE_FILES));
  });
});

describe("the hooks", () => {
  it("require the commit check and Biome before a commit, and the push check before a push", () => {
    assert.deepEqual(
      HOOKS.map((hook) => [
        hook.path,
        hook.requiredLines.map(({ line }) => line),
      ]),
      [
        [PRE_COMMIT_PATH, [CHECK_COMMIT_LINE, BIOME_LINE]],
        [PRE_PUSH_PATH, [CHECK_PUSH_LINE]],
      ],
    );
  });

  it("are inspected together with the owned files, package.json and both Biome configuration names", () => {
    assert.deepEqual(INSPECTED_PATHS, [
      PULL_REQUEST_WORKFLOW_PATH,
      PUSH_WORKFLOW_PATH,
      SKILL_PATH,
      PRE_COMMIT_PATH,
      PRE_PUSH_PATH,
      "package.json",
      "biome.json",
      "biome.jsonc",
    ]);
  });
});

describe("missingHookLines", () => {
  const preCommit = HOOKS[0].requiredLines;

  it("is empty when a line holds each marker, however the command is reached", () => {
    assert.deepEqual(
      missingHookLines(preCommit, `${CHECK_COMMIT_LINE}\n${BIOME_LINE}\n`),
      [],
    );
    assert.deepEqual(
      missingHookLines(
        preCommit,
        "pnpm exec style-guide check-commit\r\nnpx biome check --staged\r\n",
      ),
      [],
    );
    assert.deepEqual(
      missingHookLines(
        preCommit,
        `npm test\n  ${BIOME_LINE} && ${CHECK_COMMIT_LINE}`,
      ),
      [],
    );
  });

  it("returns the exact line to add for each marker no line holds", () => {
    assert.deepEqual(missingHookLines(preCommit, "npm test\n"), [
      CHECK_COMMIT_LINE,
      BIOME_LINE,
    ]);
    assert.deepEqual(missingHookLines(preCommit, `${CHECK_COMMIT_LINE}\n`), [
      BIOME_LINE,
    ]);
    assert.deepEqual(missingHookLines(preCommit, `${BIOME_LINE}\n`), [
      CHECK_COMMIT_LINE,
    ]);
    assert.deepEqual(missingHookLines(preCommit, ""), [
      CHECK_COMMIT_LINE,
      BIOME_LINE,
    ]);
  });

  it("does not count a commented-out line or another subcommand", () => {
    assert.deepEqual(
      missingHookLines(
        preCommit,
        `# ${CHECK_COMMIT_LINE}\n  # ${BIOME_LINE}\n`,
      ),
      [CHECK_COMMIT_LINE, BIOME_LINE],
    );
    assert.deepEqual(
      missingHookLines(
        preCommit,
        `${CHECK_PUSH_LINE}\nnode_modules/.bin/biome lint\n`,
      ),
      [CHECK_COMMIT_LINE, BIOME_LINE],
    );
  });
});

describe("isPinnedSpec", () => {
  const pinned = [
    "0.0.7",
    "1.2.3",
    "1.2.3-beta.1",
    "1.2.3+build.5",
    "git+https://github.com/acme/style-guide.git#0123abc",
    "git+ssh://git@github.com/acme/style-guide.git",
    "git://github.com/acme/style-guide.git",
    "github:acme/style-guide#v1.2.3",
    "acme/style-guide",
    "acme/style-guide#0123abc",
  ];
  for (const spec of pinned) {
    it(`takes ${spec}`, () => {
      assert.equal(isPinnedSpec(spec), true);
    });
  }

  const loose = [
    "^1.2.3",
    "~1.2.3",
    "1.2",
    "1.x",
    "*",
    "",
    "latest",
    ">=1.0.0",
    "workspace:*",
    "catalog:",
  ];
  const local = [
    "file:../style-guide",
    "./style-guide",
    "../style-guide/pkg",
    "https://example.com/style-guide.tgz",
  ];
  for (const spec of [...loose, ...local]) {
    it(`rejects ${JSON.stringify(spec)}`, () => {
      assert.equal(isPinnedSpec(spec), false);
    });
  }
});

describe("packageManualSteps", () => {
  it("is empty for husky, a prepare script that runs it, and an exact style-guide version", () => {
    assert.deepEqual(packageManualSteps(manifestText({})), []);
    assert.deepEqual(
      packageManualSteps(
        manifestText({ scripts: { prepare: "husky || true" } }),
      ),
      [],
    );
  });

  it("reports husky missing from devDependencies, also when it is only in dependencies", () => {
    const devDependencies = { "@pleand-inc/style-guide": "1.2.3" };
    const steps = packageManualSteps(
      manifestText({ devDependencies, dependencies: { husky: "9.1.7" } }),
    );
    assert.deepEqual(steps, ["package.json: add husky to devDependencies"]);
  });

  it("reports a missing prepare script and one that does not run husky", () => {
    const expected = [
      'package.json: add a prepare script that runs husky ("prepare": "husky")',
    ];
    assert.deepEqual(
      packageManualSteps(manifestText({ scripts: {} })),
      expected,
    );
    assert.deepEqual(
      packageManualSteps(manifestText({ scripts: undefined })),
      expected,
    );
    assert.deepEqual(
      packageManualSteps(
        manifestText({ scripts: { prepare: "npm run build" } }),
      ),
      expected,
    );
    assert.deepEqual(
      packageManualSteps(manifestText({ scripts: { prepare: "huskyish" } })),
      expected,
    );
  });

  it("reports a style-guide version that is a range, showing what it found", () => {
    const devDependencies = {
      "@pleand-inc/style-guide": "^1.2.3",
      husky: "9.1.7",
    };
    assert.deepEqual(packageManualSteps(manifestText({ devDependencies })), [
      "package.json: pin @pleand-inc/style-guide in devDependencies to an exact version or a git spec " +
        '(found "^1.2.3")',
    ]);
  });

  it("reports style-guide missing from devDependencies, which is where the workflows read it", () => {
    const steps = packageManualSteps(
      manifestText({ devDependencies: { husky: "9.1.7" } }),
    );
    assert.deepEqual(steps, [
      "package.json: add @pleand-inc/style-guide to devDependencies at an exact version",
    ]);
  });

  it("reports all three for an empty manifest", () => {
    assert.equal(packageManualSteps("{}").length, 3);
  });

  it("reports a missing or unreadable package.json as one step", () => {
    const expected = [
      "package.json: add a package.json that holds a JSON object",
    ];
    assert.deepEqual(packageManualSteps(undefined), expected);
    assert.deepEqual(packageManualSteps("{ not json"), expected);
    assert.deepEqual(packageManualSteps("[]"), expected);
  });
});

describe("the setup inspection of an empty and of a set-up repository", () => {
  it("in an empty repository: init creates all five files and both commands list the manual steps", () => {
    const inspection = inspectSetup(new Map(), RULE_FILES);
    const plan = initPlan(inspection);
    assert.deepEqual(
      plan.writes.map((write) => write.path),
      [
        PULL_REQUEST_WORKFLOW_PATH,
        PUSH_WORKFLOW_PATH,
        SKILL_PATH,
        PRE_COMMIT_PATH,
        PRE_PUSH_PATH,
      ],
    );
    assert.equal(
      plan.writes[3].content,
      `${CHECK_COMMIT_LINE}\n${BIOME_LINE}\n`,
    );
    assert.equal(plan.writes[4].content, `${CHECK_PUSH_LINE}\n`);
    assert.deepEqual(plan.lines.slice(0, 5), [
      `created    ${PULL_REQUEST_WORKFLOW_PATH}`,
      `created    ${PUSH_WORKFLOW_PATH}`,
      `created    ${SKILL_PATH}`,
      `created    ${PRE_COMMIT_PATH}`,
      `created    ${PRE_PUSH_PATH}`,
    ]);
    assert.deepEqual(plan.lines.slice(5), [
      "manual: package.json: add a package.json that holds a JSON object",
      'manual: biome.json: extend the shared configuration ("extends": ["@pleand-inc/style-guide/biome"])',
    ]);
    assert.equal(plan.exitCode, 1);

    const report = checkReport(inspection);
    assert.deepEqual(report.lines, [
      `missing: ${PULL_REQUEST_WORKFLOW_PATH} (run style-guide init)`,
      `missing: ${PUSH_WORKFLOW_PATH} (run style-guide init)`,
      `missing: ${SKILL_PATH} (run style-guide init)`,
      `missing: ${PRE_COMMIT_PATH} (run style-guide init)`,
      `missing: ${PRE_PUSH_PATH} (run style-guide init)`,
      ...plan.lines.slice(5),
    ]);
    assert.equal(report.exitCode, 1);
  });

  it("in a set-up repository: init writes nothing, reports every file unchanged, and check passes", () => {
    const inspection = inspectSetup(completeRepositoryFiles(), RULE_FILES);
    const plan = initPlan(inspection);
    assert.deepEqual(plan.writes, []);
    assert.deepEqual(plan.lines, [
      `unchanged  ${PULL_REQUEST_WORKFLOW_PATH}`,
      `unchanged  ${PUSH_WORKFLOW_PATH}`,
      `unchanged  ${SKILL_PATH}`,
      `unchanged  ${PRE_COMMIT_PATH}`,
      `unchanged  ${PRE_PUSH_PATH}`,
    ]);
    assert.equal(plan.exitCode, 0);
    assert.deepEqual(checkReport(inspection), {
      lines: ["style-guide check: the setup is current"],
      exitCode: 0,
    });
  });
});

describe("the setup inspection of the owned files", () => {
  it("an edited owned file: check names it and init rewrites it", () => {
    const files = completeRepositoryFiles();
    files.set(
      PUSH_WORKFLOW_PATH,
      contentOf(PUSH_WORKFLOW_PATH).replace(
        "timeout-minutes: 5",
        "timeout-minutes: 30",
      ),
    );
    const inspection = inspectSetup(files, RULE_FILES);
    assert.deepEqual(checkReport(inspection), {
      lines: [`differs: ${PUSH_WORKFLOW_PATH} (run style-guide init)`],
      exitCode: 1,
    });
    const plan = initPlan(inspection);
    assert.deepEqual(plan.writes, [
      { path: PUSH_WORKFLOW_PATH, content: contentOf(PUSH_WORKFLOW_PATH) },
    ]);
    assert.equal(plan.lines[1], `rewritten  ${PUSH_WORKFLOW_PATH}`);
    assert.equal(plan.exitCode, 0);
  });

  it("a skill generated from another set of rule files differs", () => {
    const inspection = inspectSetup(completeRepositoryFiles(), ["RULES.md"]);
    assert.deepEqual(checkReport(inspection).lines, [
      `differs: ${SKILL_PATH} (run style-guide init)`,
    ]);
  });

  it("an owned file checked out with CRLF line endings is current", () => {
    const files = completeRepositoryFiles();
    for (const { path, content } of ownedFiles(RULE_FILES))
      files.set(path, content.replaceAll("\n", "\r\n"));
    assert.equal(checkReport(inspectSetup(files, RULE_FILES)).exitCode, 0);
  });
});

describe("the setup inspection of the hooks", () => {
  it("an existing hook without a required line: init leaves it alone and prints the line to add", () => {
    const files = completeRepositoryFiles();
    files.set(PRE_COMMIT_PATH, "npm test\n");
    files.set(PRE_PUSH_PATH, "# nothing yet\n");
    const inspection = inspectSetup(files, RULE_FILES);
    const plan = initPlan(inspection);
    assert.deepEqual(plan.writes, []);
    assert.deepEqual(plan.lines.slice(3), [
      `incomplete ${PRE_COMMIT_PATH}`,
      `incomplete ${PRE_PUSH_PATH}`,
      `manual: add this line to ${PRE_COMMIT_PATH}: ${CHECK_COMMIT_LINE}`,
      `manual: add this line to ${PRE_COMMIT_PATH}: ${BIOME_LINE}`,
      `manual: add this line to ${PRE_PUSH_PATH}: ${CHECK_PUSH_LINE}`,
    ]);
    assert.equal(plan.exitCode, 1);
    assert.deepEqual(checkReport(inspection), {
      lines: plan.lines.slice(5),
      exitCode: 1,
    });
  });

  it("a deleted hook: check names it and init creates it again", () => {
    const files = completeRepositoryFiles();
    files.delete(PRE_PUSH_PATH);
    const inspection = inspectSetup(files, RULE_FILES);
    assert.deepEqual(checkReport(inspection), {
      lines: [`missing: ${PRE_PUSH_PATH} (run style-guide init)`],
      exitCode: 1,
    });
    assert.deepEqual(initPlan(inspection).writes, [
      { path: PRE_PUSH_PATH, content: `${CHECK_PUSH_LINE}\n` },
    ]);
  });
});

describe("the setup inspection of what init never writes", () => {
  it("the Biome configuration: either file name counts, and it must name the shared configuration", () => {
    const expected = [
      'manual: biome.json: extend the shared configuration ("extends": ["@pleand-inc/style-guide/biome"])',
    ];
    const jsonc = completeRepositoryFiles();
    jsonc.set("biome.jsonc", jsonc.get("biome.json"));
    jsonc.delete("biome.json");
    assert.equal(checkReport(inspectSetup(jsonc, RULE_FILES)).exitCode, 0);

    const own = completeRepositoryFiles();
    own.set("biome.json", '{ "linter": { "enabled": true } }');
    assert.deepEqual(
      checkReport(inspectSetup(own, RULE_FILES)).lines,
      expected,
    );

    const none = completeRepositoryFiles();
    none.delete("biome.json");
    assert.deepEqual(
      checkReport(inspectSetup(none, RULE_FILES)).lines,
      expected,
    );
    assert.equal(initPlan(inspectSetup(none, RULE_FILES)).exitCode, 1);
  });

  it("package.json steps are listed by both commands and are never written", () => {
    const files = completeRepositoryFiles();
    files.set(
      "package.json",
      manifestText({
        devDependencies: { "@pleand-inc/style-guide": "^1.2.3" },
      }),
    );
    const inspection = inspectSetup(files, RULE_FILES);
    const plan = initPlan(inspection);
    assert.deepEqual(plan.writes, []);
    assert.equal(plan.exitCode, 1);
    assert.deepEqual(checkReport(inspection).lines, plan.lines.slice(5));
    assert.equal(checkReport(inspection).lines.length, 2);
  });
});
