// The content of the files `style-guide init` owns in a consuming repository (no I/O).

/**
 * @typedef {object} WorkflowJob
 * @property {string} id
 * @property {string} name the check name GitHub shows on the commit
 * @property {string[]} permissions
 * @property {string[]} env
 * @property {string} command the style-guide subcommand the job runs
 */

export const PACKAGE_NAME = "@pleand-inc/style-guide";
export const INSTALLED_PACKAGE_PATH = `node_modules/${PACKAGE_NAME}`;
export const INSTALLED_BIN_PATH = "node_modules/.bin/style-guide";
export const GENERATED_NOTICE =
  "Generated by `style-guide init`. Do not edit by hand: `style-guide check` fails when this file differs.";

// The same commits as .github/workflows/test.yml of the style-guide repository; test/cli/setup.test.mjs compares them.
const CHECKOUT_ACTION =
  "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1";
const SETUP_NODE_ACTION =
  "actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0";

const SKILL_DESCRIPTION =
  "Use when writing, editing or reviewing code in this repository, and when creating a branch, " +
  "opening a pull request or merging one. 코드 규칙, 브랜치 흐름, 머지.";

/**
 * The shell lines of a workflow step. They run the command from the package version the repository pins, without
 * installing the repository's own dependencies. The version is read when the step runs, so a version bump leaves
 * the workflow file as it is.
 * @param {string} command
 * @returns {string[]}
 */
export function workflowRunLines(command) {
  const readPinnedSpec =
    `const v = require('./package.json').devDependencies['${PACKAGE_NAME}']; ` +
    `/^[0-9]/.test(v) ? '${PACKAGE_NAME}@' + v : v`;
  return [
    `spec="$(node -p "${readPinnedSpec}")"`,
    `npm exec --yes --package="$spec" -- style-guide ${command}`,
  ];
}

/**
 * @param {string} name a context value, such as `github.token`
 * @returns {string} the expression GitHub Actions replaces with that value
 */
function githubExpression(name) {
  return `\${{ ${name} }}`;
}

/**
 * @param {string[]} lines
 * @param {number} width
 */
function indent(lines, width) {
  return lines.map((line) => " ".repeat(width) + line);
}

/** @param {WorkflowJob} job */
function jobLines(job) {
  // Without this npm would download the Biome peer dependency just to run a command that never calls Biome.
  const env = job.env.concat('NPM_CONFIG_LEGACY_PEER_DEPS: "true"');
  return [
    `  ${job.id}:`,
    `    name: ${job.name}`,
    "    runs-on: ubuntu-latest",
    "    timeout-minutes: 5",
    "    permissions:",
    ...indent(job.permissions, 6),
    "    steps:",
    `      - uses: ${CHECKOUT_ACTION}`,
    "",
    `      - uses: ${SETUP_NODE_ACTION}`,
    "        with:",
    "          node-version: lts/*",
    "",
    `      - name: style-guide ${job.command}`,
    "        env:",
    ...indent(env, 10),
    "        run: |",
    ...indent(workflowRunLines(job.command), 10),
  ];
}

/**
 * @param {string} name
 * @param {string[]} trigger the lines under `on:`
 * @param {WorkflowJob[]} jobs
 */
function workflowFile(name, trigger, jobs) {
  const jobBlocks = jobs.map((job) => jobLines(job).join("\n")).join("\n\n");
  const lines = [
    `# ${GENERATED_NOTICE}`,
    `name: ${name}`,
    "",
    "on:",
    ...indent(trigger, 2),
    "",
  ];
  lines.push("permissions: {}", "", "jobs:", jobBlocks, "");
  return lines.join("\n");
}

export function pullRequestWorkflowFile() {
  const trigger = [
    "pull_request:",
    "  types: [opened, reopened, synchronize, edited]",
  ];
  return workflowFile("Style guide pull request", trigger, [
    {
      id: "pull-request-pairing",
      name: "pull request pairing",
      permissions: ["contents: read"],
      env: [
        `BASE_REF: ${githubExpression("github.base_ref")}`,
        `HEAD_REF: ${githubExpression("github.head_ref")}`,
      ],
      command: "check-pull-request",
    },
    {
      id: "style-guide-setup",
      name: "style guide setup",
      permissions: ["contents: read"],
      env: [],
      command: "check",
    },
  ]);
}

export function pushWorkflowFile() {
  const trigger = ["push:", "  branches:", "    - master", "    - develop"];
  return workflowFile("Style guide push", trigger, [
    {
      id: "landed-commit",
      name: "landed commit",
      permissions: ["contents: read", "pull-requests: read"],
      env: [`GITHUB_TOKEN: ${githubExpression("github.token")}`],
      command: "check-landed-commit",
    },
  ]);
}

/**
 * @param {readonly string[]} ruleFiles paths under the installed package's `rules/` directory
 * @returns {string} the agent skill that points at the rules and the branch flow of the installed package
 */
export function skillFile(ruleFiles) {
  return [
    "---",
    "name: style-guide",
    `description: ${SKILL_DESCRIPTION}`,
    "---",
    "",
    `<!-- ${GENERATED_NOTICE} -->`,
    "",
    "# style-guide",
    "",
    `이 저장소는 \`${PACKAGE_NAME}\` 패키지의 코드 규칙과 브랜치 흐름을 따릅니다.`,
    "",
    "## 규칙",
    "",
    "규칙은 아래 파일에 있습니다. `typescript/` 아래는 TypeScript 코드 규칙이고, `git/` 아래는 브랜치 흐름과 변경 이력의 규칙입니다. " +
      "코드를 쓰거나 고치거나 검토하기 전에 읽습니다.",
    "",
    ...ruleFiles.map((file) => `- \`${INSTALLED_PACKAGE_PATH}/rules/${file}\``),
    "",
    "## 브랜치 흐름",
    "",
    `브랜치 흐름은 \`${INSTALLED_PACKAGE_PATH}/rules/git/branch-flow/RULES.md\` 에 있습니다. ` +
      "브랜치를 만들거나 pull request 를 올리거나 머지하기 전에 읽습니다.",
    "",
    `- 머지는 \`${INSTALLED_BIN_PATH} merge <번호>\` 로 합니다. \`gh pr merge\` 를 직접 쓰지 않습니다.`,
    "- `master` 와 `develop` 에 직접 커밋하거나 push 하지 않습니다.",
    "",
    "## 규칙을 바꿀 때",
    "",
    `규칙은 이 저장소에서 고치지 않습니다. \`${INSTALLED_PACKAGE_PATH}\` 아래의 파일과 이 파일은 손으로 고치지 않습니다. ` +
      "규칙을 바꾸려면 style-guide 저장소에 RFC 를 올립니다.",
    "",
  ].join("\n");
}
